alias zshrc="nvim ~/.zshrc"
alias cp="cp -v"
alias mv="mv -vi"
alias rm="rm -vi"
alias lv="lvim"
alias v="nvim"
alias dotf="cd ~/.dotfiles"
alias kat="bat --theme Dracula"
alias ws="cd ~/workspace"
alias dw="cd ~/Downloads/"
alias repos="cd ~/Downloads/.repos/"
alias icat="kitty +kitten icat"
alias za="zathura"
alias p="python3"
alias r="ranger"
alias j="java -jar"
alias y="yay"
alias l="eza --icons=always -la"
alias ls='eza --icons=always'
alias ll='eza --icons=always -alh'
alias lg="lazygit"
alias ld="lazydocker"
alias calc="python3"
alias cal="cal -m -y"
alias tree="erd -I"
alias bashrc="nvim ~/.bashrc"
alias aliases="nvim ~/.dotfiles/zsh/alias.sh"
alias dot="cd ~/.dotfiles"
alias g="git"
alias tchsh="kat ~/.config/tmux/tmux.conf"
alias startdocker="sudo systemctl start docker.service"
alias maintenance="yay -Sc && sudo pacman -Scc"
alias pipx="python -m pipx"
alias vrtviewer="virt-viewer --connect=qemu:///system --domain-name win10"
