#!/bin/bash

read -p "percentage (60, 80, 90, 100) " percent

file=/etc/systemd/system/battery-charge-threshold.service

sudo sed -Eibak "s/[0-9]{2}/$percent/g" $file

sudo systemctl daemon-reload

sudo systemctl restart battery-charge-threshold.service

echo "Battery threshold changed!!"
